### ISSUE TITLE
Installing with make install DESTDIR=/tmp fails to do /etc/* files

### ISSUE THREAD

**Issue by lopippo** [tomschr/daps#693]
Greetings,

I like to test software by typically issuing the install command like this:

% make install DESTDIR=/tmp

which simulates the install process in system dir nicely.

That process just works for daps, only for the following:

```
install -m755 autobuild/daps-autobuild /tmp/usr/bin
install -m644 autobuild/daps-autobuild.rnc /tmp/usr/share/xml/daps/schema/
install -m644 autobuild/daps-autobuild.xml /tmp/usr/share/daps/init_templates
/usr/bin/xmllint --nocatalogs --format /etc/xml/catalog | \
    awk "/<\/group>/ && s == 1 {s=0;next} s == 1 {next} \
      /<group id=\"daps\">/{s=1;next} {print}" | \
      sed '/<\/catalog>/d' >build/daps_catalog.jKOD2
/usr/bin/xmllint --nocatalogs --format build/catalog.d/daps.xml | \
  awk '/<\/catalog>/{next} s == 1 {print} /<catalog/{s=1} \
    END{print "</catalog>"}' >>build/daps_catalog.jKOD2
chmod --reference=/etc/xml/catalog build/daps_catalog.jKOD2
mv build/daps_catalog.jKOD2 /etc/xml/catalog
mv: replace '/etc/xml/catalog', overriding mode 0644 (rw-r--r--)? y
mv: cannot move 'build/daps_catalog.jKOD2' to '/etc/xml/catalog': Permission denied
make[2]: *** [Makefile:1737: install-data-local] Error 1
make[2]: Leaving directory '/home/rusconi/devel/daps/build-area/unix/development'
make[1]: *** [Makefile:1538: install-am] Error 2
make[1]: Leaving directory '/home/rusconi/devel/daps/build-area/unix/development'
make: *** [Makefile:1230: install-recursive] Error 1
```

Apparently, the system configuration still wants to go to '/'.

Is it possible to fix this, as that might be useful for people using daps but not enjoying root priviledges ? Or for people like me willing to test the software outside of system directories.

Feel free to close this bug if my remark is insane :-)

Sincerely
Filippo

**Comment by fsundermeyer** [comment]
There is a special configure script to disable the XML catalog changing procedure:

`./configure --disable-edit-rootcatalog`

(also see ./confugure --help). Running configure with that switch and then your make command should do the trick.

Installing the changes to the system catalog under $DESTDIR makes little sense, since these changes need to be in the system catalog. 
In theory it would also be possible with a user defined catalog, but since the vast majority of users not even know what an XML catalog is, this would make things overly complicated. DAPS should work without it's respective catalog entries if you replace values for DOCBOOK4_PROFILE_URN and DOCBOOK5_PROFILE_URN in the system or user config file with the paths to the respective files in `$DESTDIR//usr/share/daps/daps-xslt/profiling/`.

**Comment by lopippo** [comment]
Understood, thank you! Feel free to close this issue, then!
Sincerely,
Filippo
