### ISSUE TITLE
DAPS is very slow on Ubuntu -  Could not resolve URN

### ISSUE THREAD

**Issue by MartinKoeditz** [tomschr/daps#697]
### Problem description
I use daps on Ubuntu. The app is very slow. If I run DAPS I get an error after 20 minutes of runtime. I don't have the problem on OpenSuse.

### Expected behavior
Running DAPS without errors in normal runtime.

### Steps to reproduce problem
```
web3@sgbs-ispconfig-dev:/var/www/docs05.syndesk.de/web/docs$ daps -vv -m "xml/SynDesk-stage01.xml" --styleroot "styleroot/synergy2020-ns" html
---------------

        DAPS VERSION: 3.0.0

             DOC_DIR: /var/www/clients/client1/web3/web/docs
           BUILD_DIR: /var/www/clients/client1/web3/web/docs/build
            DAPSROOT: /usr/share/daps
             DOCCONF: 
                BOOK: SynDesk-stage01

           PROFILING: On

     DOCBOOK_VERSION: 5
        DOCBOOK5_RNG: /usr/share/xml/docbook/schema/rng/5.0/docbookxi.rng
        DBSTYLE_VERS: snapshot

           STYLEROOT: /var/www/clients/client1/web3/web/docs/styleroot/synergy2020-ns
      STYLEROOT_VERS: '2.0.15'
  FALLBACK_STYLEROOT: /usr/share/xml/docbook/stylesheet/docbook-xsl-ns
   FB_STYLEROOT_VERS: Not available
            EPUB_CSS: 
            HTML_CSS: 

       PDF FORMATTER: fop
[warning] /usr/bin/fop: JVM flavor 'sun' not understood
   FORMATTER VERSION: FOP Version 2.6
   FORMATTER WRAPPER: /usr/share/daps/libexec/daps-fop
    FORMATTER CONFIG: 

            MAKE_CMD: /usr/bin/make -f /usr/share/daps/make/selector.mk -j2 -s html 
       XSLTPROCESSOR: /usr/bin/xsltproc
   XML_CATALOG_FILES: /etc/xml/catalog

---------------

Could not resolve URN "urn:x-suse:xslt:profiling:docbook50-profile.xsl" with xmlcatalog via catalog file "/etc/xml/catalog"
/usr/share/daps/make/profiling.mk:47: *** .  Stop.
```

**Comment by fsundermeyer** [comment]
Hi Martin,

DAPS 3.0 is already pretty old, latest version is DAPS 3.3.2. Would you mind trying it to see whether the error has been fixed in the meantime?
For testing purposes you can run DAPS directly from a GitHub checkout as described here:
https://github.com/openSUSE/daps/blob/main/INSTALL.adoc#5-running-daps-from-a-local-git-clone

NOTE: You may run into an issue that has been reported a few days ago, see #699 
(The reporter is currently packaging DAPS for Debian)

In case the error has not been fixed, please run daps with the `--debug` parameter. It will create a lot of output. among it the commands that are excecuted. You should be able to see which of these commands take so long.

Best regards, Frank

**Comment by lopippo** [comment]
Greetings,
I have patched the validate.mk makefile so that daps runs just fine in Debian testing.
https://packages.debian.org/bookworm/daps
Sincerely,
Filippo

**Comment by MartinKoeditz** [comment]
The new DAPS version works. Thank you.
